# Generated by Django 4.2.30 on 2026-09-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
